log whether gzip is installed

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -16,7 +16,8 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt update
-          sudo apt install -y build-essential git cmake tar gzip pigz zstd lz4
+          sudo apt install -y build-essential git cmake tar gzip zstd lz4
+          which gzip || echo "Gzip not found!"
 
       - name: Clone and Build lzbench
         run: |
